/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SupplyUni } from "./SupplyUni";

export { SupplyUni__factory } from "./factories/SupplyUni__factory";
