/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockSupplyAave } from "./MockSupplyAave";

export { MockSupplyAave__factory } from "./factories/MockSupplyAave__factory";
